/* Generated by GOB (v2.0.17)   (do not edit directly) */

#ifndef __GPILOT_APPLET_PROGRESS_PRIVATE_H__
#define __GPILOT_APPLET_PROGRESS_PRIVATE_H__

#include "gpilot-applet-progress.h"

#ifdef __cplusplus
extern "C" {
#endif /* __cplusplus */

struct _GPilotAppletProgressPrivate {
#line 23 "gpilot-applet-progress.gob"
	guint timeout_handler;
#line 16 "gpilot-applet-progress-private.h"
};

#ifdef __cplusplus
}
#endif /* __cplusplus */

#endif
