/* Generated by GOB (v2.0.17)   (do not edit directly) */

/* End world hunger, donate to the World Food Programme, http://www.wfp.org */

#define GOB_VERSION_MAJOR 2
#define GOB_VERSION_MINOR 0
#define GOB_VERSION_PATCHLEVEL 17

#define selfp (self->_priv)

#include <string.h> /* memset() */

#include "gnome-pilot-conduit-standard.h"

#include "gnome-pilot-conduit-standard-private.h"

#ifdef G_LIKELY
#define ___GOB_LIKELY(expr) G_LIKELY(expr)
#define ___GOB_UNLIKELY(expr) G_UNLIKELY(expr)
#else /* ! G_LIKELY */
#define ___GOB_LIKELY(expr) (expr)
#define ___GOB_UNLIKELY(expr) (expr)
#endif /* G_LIKELY */

#line 29 "gnome-pilot-conduit-standard.gob"

#include "gnome-pilot-conduit-backup.h"
#include "gnome-pilot-conduit-backup-private.h"
#include <sys/stat.h>
#include <unistd.h>
#include <sys/types.h>
#include <utime.h>
#include <pi-file.h>

#line 36 "gnome-pilot-conduit-standard.c"
/* self casting macros */
#define SELF(x) GNOME_PILOT_CONDUIT_STANDARD(x)
#define SELF_CONST(x) GNOME_PILOT_CONDUIT_STANDARD_CONST(x)
#define IS_SELF(x) GNOME_IS_PILOT_CONDUIT_STANDARD(x)
#define TYPE_SELF GNOME_TYPE_PILOT_CONDUIT_STANDARD
#define SELF_CLASS(x) GNOME_PILOT_CONDUIT_STANDARD_CLASS(x)

#define SELF_GET_CLASS(x) GNOME_PILOT_CONDUIT_STANDARD_GET_CLASS(x)

/* self typedefs */
typedef GnomePilotConduitStandard Self;
typedef GnomePilotConduitStandardClass SelfClass;

/* here are local prototypes */
static void ___object_set_property (GObject *object, guint property_id, const GValue *value, GParamSpec *pspec);
static void ___object_get_property (GObject *object, guint property_id, GValue *value, GParamSpec *pspec);
#line 0 "gnome-pilot-conduit-standard.gob"
static void gnome_pilot_conduit_standard_init (GnomePilotConduitStandard * o) G_GNUC_UNUSED;
#line 55 "gnome-pilot-conduit-standard.c"
#line 0 "gnome-pilot-conduit-standard.gob"
static void gnome_pilot_conduit_standard_class_init (GnomePilotConduitStandardClass * c) G_GNUC_UNUSED;
#line 58 "gnome-pilot-conduit-standard.c"

/*
 * Signal connection wrapper macro shortcuts
 */
#define self_connect__copy_to_pilot(object,func,data)	gnome_pilot_conduit_standard_connect__copy_to_pilot((object),(func),(data))
#define self_connect_after__copy_to_pilot(object,func,data)	gnome_pilot_conduit_standard_connect_after__copy_to_pilot((object),(func),(data))
#define self_connect_data__copy_to_pilot(object,func,data,destroy_data,flags)	gnome_pilot_conduit_standard_connect_data__copy_to_pilot((object),(func),(data),(destroy_data),(flags))
#define self_connect__copy_from_pilot(object,func,data)	gnome_pilot_conduit_standard_connect__copy_from_pilot((object),(func),(data))
#define self_connect_after__copy_from_pilot(object,func,data)	gnome_pilot_conduit_standard_connect_after__copy_from_pilot((object),(func),(data))
#define self_connect_data__copy_from_pilot(object,func,data,destroy_data,flags)	gnome_pilot_conduit_standard_connect_data__copy_from_pilot((object),(func),(data),(destroy_data),(flags))
#define self_connect__merge_to_pilot(object,func,data)	gnome_pilot_conduit_standard_connect__merge_to_pilot((object),(func),(data))
#define self_connect_after__merge_to_pilot(object,func,data)	gnome_pilot_conduit_standard_connect_after__merge_to_pilot((object),(func),(data))
#define self_connect_data__merge_to_pilot(object,func,data,destroy_data,flags)	gnome_pilot_conduit_standard_connect_data__merge_to_pilot((object),(func),(data),(destroy_data),(flags))
#define self_connect__merge_from_pilot(object,func,data)	gnome_pilot_conduit_standard_connect__merge_from_pilot((object),(func),(data))
#define self_connect_after__merge_from_pilot(object,func,data)	gnome_pilot_conduit_standard_connect_after__merge_from_pilot((object),(func),(data))
#define self_connect_data__merge_from_pilot(object,func,data,destroy_data,flags)	gnome_pilot_conduit_standard_connect_data__merge_from_pilot((object),(func),(data),(destroy_data),(flags))
#define self_connect__synchronize(object,func,data)	gnome_pilot_conduit_standard_connect__synchronize((object),(func),(data))
#define self_connect_after__synchronize(object,func,data)	gnome_pilot_conduit_standard_connect_after__synchronize((object),(func),(data))
#define self_connect_data__synchronize(object,func,data,destroy_data,flags)	gnome_pilot_conduit_standard_connect_data__synchronize((object),(func),(data),(destroy_data),(flags))

typedef gint  (*___Sig1) (GnomePilotConduitStandard *, gpointer , gpointer);

static void
___marshal_Sig1 (GClosure *closure,
	GValue *return_value G_GNUC_UNUSED,
	guint n_param_values,
	const GValue *param_values,
	gpointer invocation_hint G_GNUC_UNUSED,
	gpointer marshal_data)
{
	gint  v_return;
	register ___Sig1 callback;
	register GCClosure *cc = (GCClosure*) closure;
	register gpointer data1, data2;

	g_return_if_fail (n_param_values == 2);

	if (G_CCLOSURE_SWAP_DATA (closure)) {
		data1 = closure->data;
		data2 = g_value_peek_pointer (param_values + 0);
	} else {
		data1 = g_value_peek_pointer (param_values + 0);
		data2 = closure->data;
	}

	callback = (___Sig1) (marshal_data != NULL ? marshal_data : cc->callback);

	v_return = callback ((GnomePilotConduitStandard *)data1,
		(gpointer ) g_value_get_pointer (param_values + 1),
		data2);

	g_value_set_int (return_value, v_return);
}


enum {
	COPY_TO_PILOT_SIGNAL,
	COPY_FROM_PILOT_SIGNAL,
	MERGE_TO_PILOT_SIGNAL,
	MERGE_FROM_PILOT_SIGNAL,
	SYNCHRONIZE_SIGNAL,
	LAST_SIGNAL
};

enum {
	PROP_0,
	PROP_DB_NAME,
	PROP_CREATOR_ID,
	PROP_SLOW
};

static guint object_signals[LAST_SIGNAL] = {0};

/* pointer to the class of our parent */
static GnomePilotConduitClass *parent_class = NULL;

/* Short form macros */
#define self_get_db_name gnome_pilot_conduit_standard_get_db_name
#define self_set_db_name gnome_pilot_conduit_standard_set_db_name
#define self_get_creator_id gnome_pilot_conduit_standard_get_creator_id
#define self_set_creator_id gnome_pilot_conduit_standard_set_creator_id
#define self_get_slow gnome_pilot_conduit_standard_get_slow
#define self_set_slow gnome_pilot_conduit_standard_set_slow
#define self_new gnome_pilot_conduit_standard_new
#define self_copy_to_pilot gnome_pilot_conduit_standard_copy_to_pilot
#define self_copy_from_pilot gnome_pilot_conduit_standard_copy_from_pilot
#define self_merge_to_pilot gnome_pilot_conduit_standard_merge_to_pilot
#define self_merge_from_pilot gnome_pilot_conduit_standard_merge_from_pilot
#define self_synchronize gnome_pilot_conduit_standard_synchronize
GType
gnome_pilot_conduit_standard_get_type (void)
{
	static GType type = 0;

	if ___GOB_UNLIKELY(type == 0) {
		static const GTypeInfo info = {
			sizeof (GnomePilotConduitStandardClass),
			(GBaseInitFunc) NULL,
			(GBaseFinalizeFunc) NULL,
			(GClassInitFunc) gnome_pilot_conduit_standard_class_init,
			(GClassFinalizeFunc) NULL,
			NULL /* class_data */,
			sizeof (GnomePilotConduitStandard),
			0 /* n_preallocs */,
			(GInstanceInitFunc) gnome_pilot_conduit_standard_init,
			NULL
		};

		type = g_type_register_static (GNOME_TYPE_PILOT_CONDUIT, "GnomePilotConduitStandard", &info, (GTypeFlags)0);
	}

	return type;
}

/* a macro for creating a new object of our type */
#define GET_NEW ((GnomePilotConduitStandard *)g_object_new(gnome_pilot_conduit_standard_get_type(), NULL))

/* a function for creating a new object of our type */
#include <stdarg.h>
static GnomePilotConduitStandard * GET_NEW_VARG (const char *first, ...) G_GNUC_UNUSED;
static GnomePilotConduitStandard *
GET_NEW_VARG (const char *first, ...)
{
	GnomePilotConduitStandard *ret;
	va_list ap;
	va_start (ap, first);
	ret = (GnomePilotConduitStandard *)g_object_new_valist (gnome_pilot_conduit_standard_get_type (), first, ap);
	va_end (ap);
	return ret;
}

static void 
gnome_pilot_conduit_standard_init (GnomePilotConduitStandard * o G_GNUC_UNUSED)
{
#define __GOB_FUNCTION__ "Gnome:Pilot:Conduit:Standard::init"
}
#undef __GOB_FUNCTION__
static void 
gnome_pilot_conduit_standard_class_init (GnomePilotConduitStandardClass * c G_GNUC_UNUSED)
{
#define __GOB_FUNCTION__ "Gnome:Pilot:Conduit:Standard::class_init"
	GObjectClass *g_object_class G_GNUC_UNUSED = (GObjectClass*) c;

	parent_class = g_type_class_ref (GNOME_TYPE_PILOT_CONDUIT);

	object_signals[COPY_TO_PILOT_SIGNAL] =
		g_signal_new ("copy_to_pilot",
			G_TYPE_FROM_CLASS (g_object_class),
			(GSignalFlags)(G_SIGNAL_RUN_LAST | G_SIGNAL_ACTION),
			G_STRUCT_OFFSET (GnomePilotConduitStandardClass, copy_to_pilot),
			NULL, NULL,
			___marshal_Sig1,
			G_TYPE_INT, 1,
			G_TYPE_POINTER);
	if ___GOB_UNLIKELY(sizeof(int ) != sizeof(gint ) || sizeof(GnomePilotDBInfo * ) != sizeof(gpointer ) || parent_class == NULL /* avoid warning */) {
		g_error("gnome-pilot-conduit-standard.gob line 59: Type mismatch of \"copy_to_pilot\" signal signature");
	}
	object_signals[COPY_FROM_PILOT_SIGNAL] =
		g_signal_new ("copy_from_pilot",
			G_TYPE_FROM_CLASS (g_object_class),
			(GSignalFlags)(G_SIGNAL_RUN_LAST | G_SIGNAL_ACTION),
			G_STRUCT_OFFSET (GnomePilotConduitStandardClass, copy_from_pilot),
			NULL, NULL,
			___marshal_Sig1,
			G_TYPE_INT, 1,
			G_TYPE_POINTER);
	if ___GOB_UNLIKELY(sizeof(int ) != sizeof(gint ) || sizeof(GnomePilotDBInfo * ) != sizeof(gpointer ) || parent_class == NULL /* avoid warning */) {
		g_error("gnome-pilot-conduit-standard.gob line 62: Type mismatch of \"copy_from_pilot\" signal signature");
	}
	object_signals[MERGE_TO_PILOT_SIGNAL] =
		g_signal_new ("merge_to_pilot",
			G_TYPE_FROM_CLASS (g_object_class),
			(GSignalFlags)(G_SIGNAL_RUN_LAST | G_SIGNAL_ACTION),
			G_STRUCT_OFFSET (GnomePilotConduitStandardClass, merge_to_pilot),
			NULL, NULL,
			___marshal_Sig1,
			G_TYPE_INT, 1,
			G_TYPE_POINTER);
	if ___GOB_UNLIKELY(sizeof(int ) != sizeof(gint ) || sizeof(GnomePilotDBInfo * ) != sizeof(gpointer ) || parent_class == NULL /* avoid warning */) {
		g_error("gnome-pilot-conduit-standard.gob line 65: Type mismatch of \"merge_to_pilot\" signal signature");
	}
	object_signals[MERGE_FROM_PILOT_SIGNAL] =
		g_signal_new ("merge_from_pilot",
			G_TYPE_FROM_CLASS (g_object_class),
			(GSignalFlags)(G_SIGNAL_RUN_LAST | G_SIGNAL_ACTION),
			G_STRUCT_OFFSET (GnomePilotConduitStandardClass, merge_from_pilot),
			NULL, NULL,
			___marshal_Sig1,
			G_TYPE_INT, 1,
			G_TYPE_POINTER);
	if ___GOB_UNLIKELY(sizeof(int ) != sizeof(gint ) || sizeof(GnomePilotDBInfo * ) != sizeof(gpointer ) || parent_class == NULL /* avoid warning */) {
		g_error("gnome-pilot-conduit-standard.gob line 68: Type mismatch of \"merge_from_pilot\" signal signature");
	}
	object_signals[SYNCHRONIZE_SIGNAL] =
		g_signal_new ("synchronize",
			G_TYPE_FROM_CLASS (g_object_class),
			(GSignalFlags)(G_SIGNAL_RUN_LAST | G_SIGNAL_ACTION),
			G_STRUCT_OFFSET (GnomePilotConduitStandardClass, synchronize),
			NULL, NULL,
			___marshal_Sig1,
			G_TYPE_INT, 1,
			G_TYPE_POINTER);
	if ___GOB_UNLIKELY(sizeof(int ) != sizeof(gint ) || sizeof(GnomePilotDBInfo * ) != sizeof(gpointer ) || parent_class == NULL /* avoid warning */) {
		g_error("gnome-pilot-conduit-standard.gob line 71: Type mismatch of \"synchronize\" signal signature");
	}

	c->copy_to_pilot = NULL;
	c->copy_from_pilot = NULL;
	c->merge_to_pilot = NULL;
	c->merge_from_pilot = NULL;
	c->synchronize = NULL;
	g_object_class->get_property = ___object_get_property;
	g_object_class->set_property = ___object_set_property;
    {
	GParamSpec   *param_spec;

	param_spec = g_param_spec_pointer ("db_name", NULL, NULL,
		(GParamFlags)(G_PARAM_READABLE | G_PARAM_WRITABLE | G_PARAM_CONSTRUCT));
	g_object_class_install_property (g_object_class,
		PROP_DB_NAME, param_spec);
	param_spec = g_param_spec_int ("creator_id", NULL, NULL,
		G_MININT, G_MAXINT,
		0,
		(GParamFlags)(G_PARAM_READABLE | G_PARAM_WRITABLE | G_PARAM_CONSTRUCT));
	g_object_class_install_property (g_object_class,
		PROP_CREATOR_ID, param_spec);
	param_spec = g_param_spec_boolean ("slow", NULL, NULL,
		FALSE,
		(GParamFlags)(G_PARAM_READABLE | G_PARAM_WRITABLE | G_PARAM_CONSTRUCT));
	g_object_class_install_property (g_object_class,
		PROP_SLOW, param_spec);
    }
}
#undef __GOB_FUNCTION__

static void
___object_set_property (GObject *object,
	guint property_id,
	const GValue *VAL G_GNUC_UNUSED,
	GParamSpec *pspec G_GNUC_UNUSED)
#define __GOB_FUNCTION__ "Gnome:Pilot:Conduit:Standard::set_property"
{
	GnomePilotConduitStandard *self G_GNUC_UNUSED;

	self = GNOME_PILOT_CONDUIT_STANDARD (object);

	switch (property_id) {
	case PROP_DB_NAME:
	{	char *  ARG G_GNUC_UNUSED = (char * ) g_value_get_pointer (VAL);
		{
#line 41 "gnome-pilot-conduit-standard.gob"
g_free (self->db_name); self->db_name = g_strdup (ARG);
#line 311 "gnome-pilot-conduit-standard.c"
		}
		break;
	}
	case PROP_CREATOR_ID:
	{	guint32  ARG G_GNUC_UNUSED = (guint32 ) g_value_get_int (VAL);
		{
#line 44 "gnome-pilot-conduit-standard.gob"
self->creator_id = ARG;
#line 320 "gnome-pilot-conduit-standard.c"
		}
		break;
	}
	case PROP_SLOW:
	{	gboolean  ARG G_GNUC_UNUSED = (gboolean ) g_value_get_boolean (VAL);
		{
#line 47 "gnome-pilot-conduit-standard.gob"
self->slow = ARG;
#line 329 "gnome-pilot-conduit-standard.c"
		}
		break;
	}
	default:
/* Apparently in g++ this is needed, glib is b0rk */
#ifndef __PRETTY_FUNCTION__
#  undef G_STRLOC
#  define G_STRLOC	__FILE__ ":" G_STRINGIFY (__LINE__)
#endif
		G_OBJECT_WARN_INVALID_PROPERTY_ID (object, property_id, pspec);
		break;
	}
}
#undef __GOB_FUNCTION__

static void
___object_get_property (GObject *object,
	guint property_id,
	GValue *VAL G_GNUC_UNUSED,
	GParamSpec *pspec G_GNUC_UNUSED)
#define __GOB_FUNCTION__ "Gnome:Pilot:Conduit:Standard::get_property"
{
	GnomePilotConduitStandard *self G_GNUC_UNUSED;

	self = GNOME_PILOT_CONDUIT_STANDARD (object);

	switch (property_id) {
	case PROP_DB_NAME:
	{	char *  ARG;
	memset (&ARG, 0, sizeof (char * ));
		{
#line 41 "gnome-pilot-conduit-standard.gob"
ARG = self->db_name;
#line 363 "gnome-pilot-conduit-standard.c"
		}
		g_value_set_pointer (VAL, ARG);
		break;
	}
	case PROP_CREATOR_ID:
	{	guint32  ARG;
	memset (&ARG, 0, sizeof (guint32 ));
		{
#line 44 "gnome-pilot-conduit-standard.gob"
ARG = self->creator_id;
#line 374 "gnome-pilot-conduit-standard.c"
		}
		g_value_set_int (VAL, ARG);
		break;
	}
	case PROP_SLOW:
	{	gboolean  ARG;
	memset (&ARG, 0, sizeof (gboolean ));
		{
#line 47 "gnome-pilot-conduit-standard.gob"
ARG = self->slow;
#line 385 "gnome-pilot-conduit-standard.c"
		}
		g_value_set_boolean (VAL, ARG);
		break;
	}
	default:
/* Apparently in g++ this is needed, glib is b0rk */
#ifndef __PRETTY_FUNCTION__
#  undef G_STRLOC
#  define G_STRLOC	__FILE__ ":" G_STRINGIFY (__LINE__)
#endif
		G_OBJECT_WARN_INVALID_PROPERTY_ID (object, property_id, pspec);
		break;
	}
}
#undef __GOB_FUNCTION__



#line 41 "gnome-pilot-conduit-standard.gob"
char * 
gnome_pilot_conduit_standard_get_db_name (GnomePilotConduitStandard * self)
{
#line 408 "gnome-pilot-conduit-standard.c"
#define __GOB_FUNCTION__ "Gnome:Pilot:Conduit:Standard::get_db_name"
{
#line 41 "gnome-pilot-conduit-standard.gob"
		char* val; g_object_get (G_OBJECT (self), "db_name", &val, NULL); return val;
}}
#line 414 "gnome-pilot-conduit-standard.c"
#undef __GOB_FUNCTION__

#line 41 "gnome-pilot-conduit-standard.gob"
void 
gnome_pilot_conduit_standard_set_db_name (GnomePilotConduitStandard * self, char * val)
{
#line 421 "gnome-pilot-conduit-standard.c"
#define __GOB_FUNCTION__ "Gnome:Pilot:Conduit:Standard::set_db_name"
{
#line 41 "gnome-pilot-conduit-standard.gob"
		g_object_set (G_OBJECT (self), "db_name", val, NULL);
}}
#line 427 "gnome-pilot-conduit-standard.c"
#undef __GOB_FUNCTION__

#line 44 "gnome-pilot-conduit-standard.gob"
guint32 
gnome_pilot_conduit_standard_get_creator_id (GnomePilotConduitStandard * self)
{
#line 434 "gnome-pilot-conduit-standard.c"
#define __GOB_FUNCTION__ "Gnome:Pilot:Conduit:Standard::get_creator_id"
{
#line 44 "gnome-pilot-conduit-standard.gob"
		guint32 val; g_object_get (G_OBJECT (self), "creator_id", &val, NULL); return val;
}}
#line 440 "gnome-pilot-conduit-standard.c"
#undef __GOB_FUNCTION__

#line 44 "gnome-pilot-conduit-standard.gob"
void 
gnome_pilot_conduit_standard_set_creator_id (GnomePilotConduitStandard * self, guint32 val)
{
#line 447 "gnome-pilot-conduit-standard.c"
#define __GOB_FUNCTION__ "Gnome:Pilot:Conduit:Standard::set_creator_id"
{
#line 44 "gnome-pilot-conduit-standard.gob"
		g_object_set (G_OBJECT (self), "creator_id", val, NULL);
}}
#line 453 "gnome-pilot-conduit-standard.c"
#undef __GOB_FUNCTION__

#line 47 "gnome-pilot-conduit-standard.gob"
gboolean 
gnome_pilot_conduit_standard_get_slow (GnomePilotConduitStandard * self)
{
#line 460 "gnome-pilot-conduit-standard.c"
#define __GOB_FUNCTION__ "Gnome:Pilot:Conduit:Standard::get_slow"
{
#line 47 "gnome-pilot-conduit-standard.gob"
		gboolean val; g_object_get (G_OBJECT (self), "slow", &val, NULL); return val;
}}
#line 466 "gnome-pilot-conduit-standard.c"
#undef __GOB_FUNCTION__

#line 47 "gnome-pilot-conduit-standard.gob"
void 
gnome_pilot_conduit_standard_set_slow (GnomePilotConduitStandard * self, gboolean val)
{
#line 473 "gnome-pilot-conduit-standard.c"
#define __GOB_FUNCTION__ "Gnome:Pilot:Conduit:Standard::set_slow"
{
#line 47 "gnome-pilot-conduit-standard.gob"
		g_object_set (G_OBJECT (self), "slow", val, NULL);
}}
#line 479 "gnome-pilot-conduit-standard.c"
#undef __GOB_FUNCTION__

#line 49 "gnome-pilot-conduit-standard.gob"
GObject * 
gnome_pilot_conduit_standard_new (char * db_name, guint32 creator_id, GPilotPilot * pilot)
{
#line 486 "gnome-pilot-conduit-standard.c"
#define __GOB_FUNCTION__ "Gnome:Pilot:Conduit:Standard::new"
{
#line 50 "gnome-pilot-conduit-standard.gob"
	
		GnomePilotConduitStandard *ret = SELF (g_object_new (TYPE_SELF, 
								       "GnomePilotConduit::pilot", pilot, 
								       NULL));
		self_set_creator_id (ret, creator_id);
		self_set_db_name (ret, db_name);
		return G_OBJECT (ret);
	}}
#line 498 "gnome-pilot-conduit-standard.c"
#undef __GOB_FUNCTION__

#line 59 "gnome-pilot-conduit-standard.gob"
int 
gnome_pilot_conduit_standard_copy_to_pilot (GnomePilotConduitStandard * self, GnomePilotDBInfo * dbinfo)
{
#line 505 "gnome-pilot-conduit-standard.c"
	GValue ___param_values[2];
	GValue ___return_val;

memset (&___return_val, 0, sizeof (___return_val));
memset (&___param_values, 0, sizeof (___param_values));

#line 59 "gnome-pilot-conduit-standard.gob"
	g_return_val_if_fail (self != NULL, (int )0);
#line 59 "gnome-pilot-conduit-standard.gob"
	g_return_val_if_fail (GNOME_IS_PILOT_CONDUIT_STANDARD (self), (int )0);
#line 59 "gnome-pilot-conduit-standard.gob"
	g_return_val_if_fail (dbinfo != NULL, (int )0);
#line 518 "gnome-pilot-conduit-standard.c"

	___param_values[0].g_type = 0;
	g_value_init (&___param_values[0], G_TYPE_FROM_INSTANCE (self));
	g_value_set_instance (&___param_values[0], (gpointer) self);

	___param_values[1].g_type = 0;
	g_value_init (&___param_values[1], G_TYPE_POINTER);
	g_value_set_pointer (&___param_values[1], (gpointer ) dbinfo);

	g_value_init (&___return_val, G_TYPE_INT);

	g_signal_emitv (___param_values,
		object_signals[COPY_TO_PILOT_SIGNAL],
		0 /* detail */,
		&___return_val);

	g_value_unset (&___param_values[0]);
	g_value_unset (&___param_values[1]);

	{
		int  ___ret = (gint ) g_value_get_int (&___return_val);
		g_value_unset (&___return_val);
		return ___ret;
	}
}

#line 62 "gnome-pilot-conduit-standard.gob"
int 
gnome_pilot_conduit_standard_copy_from_pilot (GnomePilotConduitStandard * self, GnomePilotDBInfo * dbinfo)
{
#line 549 "gnome-pilot-conduit-standard.c"
	GValue ___param_values[2];
	GValue ___return_val;

memset (&___return_val, 0, sizeof (___return_val));
memset (&___param_values, 0, sizeof (___param_values));

#line 62 "gnome-pilot-conduit-standard.gob"
	g_return_val_if_fail (self != NULL, (int )0);
#line 62 "gnome-pilot-conduit-standard.gob"
	g_return_val_if_fail (GNOME_IS_PILOT_CONDUIT_STANDARD (self), (int )0);
#line 62 "gnome-pilot-conduit-standard.gob"
	g_return_val_if_fail (dbinfo != NULL, (int )0);
#line 562 "gnome-pilot-conduit-standard.c"

	___param_values[0].g_type = 0;
	g_value_init (&___param_values[0], G_TYPE_FROM_INSTANCE (self));
	g_value_set_instance (&___param_values[0], (gpointer) self);

	___param_values[1].g_type = 0;
	g_value_init (&___param_values[1], G_TYPE_POINTER);
	g_value_set_pointer (&___param_values[1], (gpointer ) dbinfo);

	g_value_init (&___return_val, G_TYPE_INT);

	g_signal_emitv (___param_values,
		object_signals[COPY_FROM_PILOT_SIGNAL],
		0 /* detail */,
		&___return_val);

	g_value_unset (&___param_values[0]);
	g_value_unset (&___param_values[1]);

	{
		int  ___ret = (gint ) g_value_get_int (&___return_val);
		g_value_unset (&___return_val);
		return ___ret;
	}
}

#line 65 "gnome-pilot-conduit-standard.gob"
int 
gnome_pilot_conduit_standard_merge_to_pilot (GnomePilotConduitStandard * self, GnomePilotDBInfo * dbinfo)
{
#line 593 "gnome-pilot-conduit-standard.c"
	GValue ___param_values[2];
	GValue ___return_val;

memset (&___return_val, 0, sizeof (___return_val));
memset (&___param_values, 0, sizeof (___param_values));

#line 65 "gnome-pilot-conduit-standard.gob"
	g_return_val_if_fail (self != NULL, (int )0);
#line 65 "gnome-pilot-conduit-standard.gob"
	g_return_val_if_fail (GNOME_IS_PILOT_CONDUIT_STANDARD (self), (int )0);
#line 65 "gnome-pilot-conduit-standard.gob"
	g_return_val_if_fail (dbinfo != NULL, (int )0);
#line 606 "gnome-pilot-conduit-standard.c"

	___param_values[0].g_type = 0;
	g_value_init (&___param_values[0], G_TYPE_FROM_INSTANCE (self));
	g_value_set_instance (&___param_values[0], (gpointer) self);

	___param_values[1].g_type = 0;
	g_value_init (&___param_values[1], G_TYPE_POINTER);
	g_value_set_pointer (&___param_values[1], (gpointer ) dbinfo);

	g_value_init (&___return_val, G_TYPE_INT);

	g_signal_emitv (___param_values,
		object_signals[MERGE_TO_PILOT_SIGNAL],
		0 /* detail */,
		&___return_val);

	g_value_unset (&___param_values[0]);
	g_value_unset (&___param_values[1]);

	{
		int  ___ret = (gint ) g_value_get_int (&___return_val);
		g_value_unset (&___return_val);
		return ___ret;
	}
}

#line 68 "gnome-pilot-conduit-standard.gob"
int 
gnome_pilot_conduit_standard_merge_from_pilot (GnomePilotConduitStandard * self, GnomePilotDBInfo * dbinfo)
{
#line 637 "gnome-pilot-conduit-standard.c"
	GValue ___param_values[2];
	GValue ___return_val;

memset (&___return_val, 0, sizeof (___return_val));
memset (&___param_values, 0, sizeof (___param_values));

#line 68 "gnome-pilot-conduit-standard.gob"
	g_return_val_if_fail (self != NULL, (int )0);
#line 68 "gnome-pilot-conduit-standard.gob"
	g_return_val_if_fail (GNOME_IS_PILOT_CONDUIT_STANDARD (self), (int )0);
#line 68 "gnome-pilot-conduit-standard.gob"
	g_return_val_if_fail (dbinfo != NULL, (int )0);
#line 650 "gnome-pilot-conduit-standard.c"

	___param_values[0].g_type = 0;
	g_value_init (&___param_values[0], G_TYPE_FROM_INSTANCE (self));
	g_value_set_instance (&___param_values[0], (gpointer) self);

	___param_values[1].g_type = 0;
	g_value_init (&___param_values[1], G_TYPE_POINTER);
	g_value_set_pointer (&___param_values[1], (gpointer ) dbinfo);

	g_value_init (&___return_val, G_TYPE_INT);

	g_signal_emitv (___param_values,
		object_signals[MERGE_FROM_PILOT_SIGNAL],
		0 /* detail */,
		&___return_val);

	g_value_unset (&___param_values[0]);
	g_value_unset (&___param_values[1]);

	{
		int  ___ret = (gint ) g_value_get_int (&___return_val);
		g_value_unset (&___return_val);
		return ___ret;
	}
}

#line 71 "gnome-pilot-conduit-standard.gob"
int 
gnome_pilot_conduit_standard_synchronize (GnomePilotConduitStandard * self, GnomePilotDBInfo * dbinfo)
{
#line 681 "gnome-pilot-conduit-standard.c"
	GValue ___param_values[2];
	GValue ___return_val;

memset (&___return_val, 0, sizeof (___return_val));
memset (&___param_values, 0, sizeof (___param_values));

#line 71 "gnome-pilot-conduit-standard.gob"
	g_return_val_if_fail (self != NULL, (int )0);
#line 71 "gnome-pilot-conduit-standard.gob"
	g_return_val_if_fail (GNOME_IS_PILOT_CONDUIT_STANDARD (self), (int )0);
#line 71 "gnome-pilot-conduit-standard.gob"
	g_return_val_if_fail (dbinfo != NULL, (int )0);
#line 694 "gnome-pilot-conduit-standard.c"

	___param_values[0].g_type = 0;
	g_value_init (&___param_values[0], G_TYPE_FROM_INSTANCE (self));
	g_value_set_instance (&___param_values[0], (gpointer) self);

	___param_values[1].g_type = 0;
	g_value_init (&___param_values[1], G_TYPE_POINTER);
	g_value_set_pointer (&___param_values[1], (gpointer ) dbinfo);

	g_value_init (&___return_val, G_TYPE_INT);

	g_signal_emitv (___param_values,
		object_signals[SYNCHRONIZE_SIGNAL],
		0 /* detail */,
		&___return_val);

	g_value_unset (&___param_values[0]);
	g_value_unset (&___param_values[1]);

	{
		int  ___ret = (gint ) g_value_get_int (&___return_val);
		g_value_unset (&___return_val);
		return ___ret;
	}
}
