/* Generated by GOB (v2.0.17)   (do not edit directly) */

/* End world hunger, donate to the World Food Programme, http://www.wfp.org */

#define GOB_VERSION_MAJOR 2
#define GOB_VERSION_MINOR 0
#define GOB_VERSION_PATCHLEVEL 17

#define selfp (self->_priv)

#include <string.h> /* memset() */

#ifdef G_LIKELY
#define ___GOB_LIKELY(expr) G_LIKELY(expr)
#define ___GOB_UNLIKELY(expr) G_UNLIKELY(expr)
#else /* ! G_LIKELY */
#define ___GOB_LIKELY(expr) (expr)
#define ___GOB_UNLIKELY(expr) (expr)
#endif /* G_LIKELY */

#line 33 "gnome-pilot-conduit-backup.gob"

#include "gnome-pilot-conduit-backup.h"
#include "gnome-pilot-conduit-backup-private.h"
#include <sys/stat.h>
#include <unistd.h>
#include <sys/types.h>
#include <utime.h>
#include <pi-file.h>

#line 32 "gnome-pilot-conduit-backup.c"
/* self casting macros */
#define SELF(x) GNOME_PILOT_CONDUIT_BACKUP(x)
#define SELF_CONST(x) GNOME_PILOT_CONDUIT_BACKUP_CONST(x)
#define IS_SELF(x) GNOME_IS_PILOT_CONDUIT_BACKUP(x)
#define TYPE_SELF GNOME_TYPE_PILOT_CONDUIT_BACKUP
#define SELF_CLASS(x) GNOME_PILOT_CONDUIT_BACKUP_CLASS(x)

#define SELF_GET_CLASS(x) GNOME_PILOT_CONDUIT_BACKUP_GET_CLASS(x)

/* self typedefs */
typedef GnomePilotConduitBackup Self;
typedef GnomePilotConduitBackupClass SelfClass;

/* here are local prototypes */
static void ___object_set_property (GObject *object, guint property_id, const GValue *value, GParamSpec *pspec);
static void ___object_get_property (GObject *object, guint property_id, GValue *value, GParamSpec *pspec);
#line 0 "gnome-pilot-conduit-backup.gob"
static void gnome_pilot_conduit_backup_init (GnomePilotConduitBackup * o) G_GNUC_UNUSED;
#line 51 "gnome-pilot-conduit-backup.c"
#line 0 "gnome-pilot-conduit-backup.gob"
static void gnome_pilot_conduit_backup_class_init (GnomePilotConduitBackupClass * c) G_GNUC_UNUSED;
#line 54 "gnome-pilot-conduit-backup.c"

/*
 * Signal connection wrapper macro shortcuts
 */
#define self_connect__backup(object,func,data)	gnome_pilot_conduit_backup_connect__backup((object),(func),(data))
#define self_connect_after__backup(object,func,data)	gnome_pilot_conduit_backup_connect_after__backup((object),(func),(data))
#define self_connect_data__backup(object,func,data,destroy_data,flags)	gnome_pilot_conduit_backup_connect_data__backup((object),(func),(data),(destroy_data),(flags))
#define self_connect__restore(object,func,data)	gnome_pilot_conduit_backup_connect__restore((object),(func),(data))
#define self_connect_after__restore(object,func,data)	gnome_pilot_conduit_backup_connect_after__restore((object),(func),(data))
#define self_connect_data__restore(object,func,data,destroy_data,flags)	gnome_pilot_conduit_backup_connect_data__restore((object),(func),(data),(destroy_data),(flags))

typedef gint  (*___Sig1) (GnomePilotConduitBackup *, gpointer , gpointer);

static void
___marshal_Sig1 (GClosure *closure,
	GValue *return_value G_GNUC_UNUSED,
	guint n_param_values,
	const GValue *param_values,
	gpointer invocation_hint G_GNUC_UNUSED,
	gpointer marshal_data)
{
	gint  v_return;
	register ___Sig1 callback;
	register GCClosure *cc = (GCClosure*) closure;
	register gpointer data1, data2;

	g_return_if_fail (n_param_values == 2);

	if (G_CCLOSURE_SWAP_DATA (closure)) {
		data1 = closure->data;
		data2 = g_value_peek_pointer (param_values + 0);
	} else {
		data1 = g_value_peek_pointer (param_values + 0);
		data2 = closure->data;
	}

	callback = (___Sig1) (marshal_data != NULL ? marshal_data : cc->callback);

	v_return = callback ((GnomePilotConduitBackup *)data1,
		(gpointer ) g_value_get_pointer (param_values + 1),
		data2);

	g_value_set_int (return_value, v_return);
}


typedef gint  (*___Sig2) (GnomePilotConduitBackup *, gint , gpointer , gpointer , gpointer , gpointer);

static void
___marshal_Sig2 (GClosure *closure,
	GValue *return_value G_GNUC_UNUSED,
	guint n_param_values,
	const GValue *param_values,
	gpointer invocation_hint G_GNUC_UNUSED,
	gpointer marshal_data)
{
	gint  v_return;
	register ___Sig2 callback;
	register GCClosure *cc = (GCClosure*) closure;
	register gpointer data1, data2;

	g_return_if_fail (n_param_values == 5);

	if (G_CCLOSURE_SWAP_DATA (closure)) {
		data1 = closure->data;
		data2 = g_value_peek_pointer (param_values + 0);
	} else {
		data1 = g_value_peek_pointer (param_values + 0);
		data2 = closure->data;
	}

	callback = (___Sig2) (marshal_data != NULL ? marshal_data : cc->callback);

	v_return = callback ((GnomePilotConduitBackup *)data1,
		(gint ) g_value_get_int (param_values + 1),
		(gpointer ) g_value_get_pointer (param_values + 2),
		(gpointer ) g_value_get_pointer (param_values + 3),
		(gpointer ) g_value_get_pointer (param_values + 4),
		data2);

	g_value_set_int (return_value, v_return);
}


enum {
	BACKUP_SIGNAL,
	RESTORE_SIGNAL,
	LAST_SIGNAL
};

enum {
	PROP_0,
	PROP_PILOT
};

static guint object_signals[LAST_SIGNAL] = {0};

/* pointer to the class of our parent */
static GnomePilotConduitClass *parent_class = NULL;

/* Short form macros */
#define self_new gnome_pilot_conduit_backup_new
#define self_backup gnome_pilot_conduit_backup_backup
#define self_restore gnome_pilot_conduit_backup_restore
GType
gnome_pilot_conduit_backup_get_type (void)
{
	static GType type = 0;

	if ___GOB_UNLIKELY(type == 0) {
		static const GTypeInfo info = {
			sizeof (GnomePilotConduitBackupClass),
			(GBaseInitFunc) NULL,
			(GBaseFinalizeFunc) NULL,
			(GClassInitFunc) gnome_pilot_conduit_backup_class_init,
			(GClassFinalizeFunc) NULL,
			NULL /* class_data */,
			sizeof (GnomePilotConduitBackup),
			0 /* n_preallocs */,
			(GInstanceInitFunc) gnome_pilot_conduit_backup_init,
			NULL
		};

		type = g_type_register_static (GNOME_TYPE_PILOT_CONDUIT, "GnomePilotConduitBackup", &info, (GTypeFlags)0);
	}

	return type;
}

/* a macro for creating a new object of our type */
#define GET_NEW ((GnomePilotConduitBackup *)g_object_new(gnome_pilot_conduit_backup_get_type(), NULL))

/* a function for creating a new object of our type */
#include <stdarg.h>
static GnomePilotConduitBackup * GET_NEW_VARG (const char *first, ...) G_GNUC_UNUSED;
static GnomePilotConduitBackup *
GET_NEW_VARG (const char *first, ...)
{
	GnomePilotConduitBackup *ret;
	va_list ap;
	va_start (ap, first);
	ret = (GnomePilotConduitBackup *)g_object_new_valist (gnome_pilot_conduit_backup_get_type (), first, ap);
	va_end (ap);
	return ret;
}

static void 
gnome_pilot_conduit_backup_init (GnomePilotConduitBackup * o G_GNUC_UNUSED)
{
#define __GOB_FUNCTION__ "Gnome:Pilot:Conduit:Backup::init"
}
#undef __GOB_FUNCTION__
static void 
gnome_pilot_conduit_backup_class_init (GnomePilotConduitBackupClass * c G_GNUC_UNUSED)
{
#define __GOB_FUNCTION__ "Gnome:Pilot:Conduit:Backup::class_init"
	GObjectClass *g_object_class G_GNUC_UNUSED = (GObjectClass*) c;

	parent_class = g_type_class_ref (GNOME_TYPE_PILOT_CONDUIT);

	object_signals[BACKUP_SIGNAL] =
		g_signal_new ("backup",
			G_TYPE_FROM_CLASS (g_object_class),
			(GSignalFlags)(G_SIGNAL_RUN_LAST | G_SIGNAL_ACTION),
			G_STRUCT_OFFSET (GnomePilotConduitBackupClass, backup),
			NULL, NULL,
			___marshal_Sig1,
			G_TYPE_INT, 1,
			G_TYPE_POINTER);
	if ___GOB_UNLIKELY(sizeof(int ) != sizeof(gint ) || sizeof(GnomePilotDBInfo * ) != sizeof(gpointer ) || parent_class == NULL /* avoid warning */) {
		g_error("gnome-pilot-conduit-backup.gob line 62: Type mismatch of \"backup\" signal signature");
	}
	object_signals[RESTORE_SIGNAL] =
		g_signal_new ("restore",
			G_TYPE_FROM_CLASS (g_object_class),
			(GSignalFlags)(G_SIGNAL_RUN_LAST | G_SIGNAL_ACTION),
			G_STRUCT_OFFSET (GnomePilotConduitBackupClass, restore),
			NULL, NULL,
			___marshal_Sig2,
			G_TYPE_INT, 4,
			G_TYPE_INT,
			G_TYPE_POINTER,
			G_TYPE_POINTER,
			G_TYPE_POINTER);
	if ___GOB_UNLIKELY(sizeof(int ) != sizeof(gint ) || sizeof(int ) != sizeof(gint ) || sizeof(char * ) != sizeof(gpointer ) || sizeof(GnomePilotConduitBackupRestore ) != sizeof(gpointer ) || sizeof(gpointer ) != sizeof(gpointer ) || parent_class == NULL /* avoid warning */) {
		g_error("gnome-pilot-conduit-backup.gob line 66: Type mismatch of \"restore\" signal signature");
	}

	c->backup = NULL;
	c->restore = NULL;
	g_object_class->get_property = ___object_get_property;
	g_object_class->set_property = ___object_set_property;
    {
	GParamSpec   *param_spec;

	param_spec = g_param_spec_pointer ("pilot", NULL, NULL,
		(GParamFlags)(G_PARAM_READABLE | G_PARAM_WRITABLE));
	g_object_class_install_property (g_object_class,
		PROP_PILOT, param_spec);
    }
}
#undef __GOB_FUNCTION__

static void
___object_set_property (GObject *object,
	guint property_id,
	const GValue *VAL G_GNUC_UNUSED,
	GParamSpec *pspec G_GNUC_UNUSED)
#define __GOB_FUNCTION__ "Gnome:Pilot:Conduit:Backup::set_property"
{
	GnomePilotConduitBackup *self G_GNUC_UNUSED;

	self = GNOME_PILOT_CONDUIT_BACKUP (object);

	switch (property_id) {
	case PROP_PILOT:
	{	GPilotPilot *  ARG G_GNUC_UNUSED = (GPilotPilot * ) g_value_get_pointer (VAL);
		{
#line 49 "gnome-pilot-conduit-backup.gob"

		self->pilot = ARG;
	
#line 277 "gnome-pilot-conduit-backup.c"
		}
		break;
	}
	default:
/* Apparently in g++ this is needed, glib is b0rk */
#ifndef __PRETTY_FUNCTION__
#  undef G_STRLOC
#  define G_STRLOC	__FILE__ ":" G_STRINGIFY (__LINE__)
#endif
		G_OBJECT_WARN_INVALID_PROPERTY_ID (object, property_id, pspec);
		break;
	}
}
#undef __GOB_FUNCTION__

static void
___object_get_property (GObject *object,
	guint property_id,
	GValue *VAL G_GNUC_UNUSED,
	GParamSpec *pspec G_GNUC_UNUSED)
#define __GOB_FUNCTION__ "Gnome:Pilot:Conduit:Backup::get_property"
{
	GnomePilotConduitBackup *self G_GNUC_UNUSED;

	self = GNOME_PILOT_CONDUIT_BACKUP (object);

	switch (property_id) {
	case PROP_PILOT:
	{	GPilotPilot *  ARG;
	memset (&ARG, 0, sizeof (GPilotPilot * ));
		{
#line 46 "gnome-pilot-conduit-backup.gob"

		ARG = self->pilot;
	
#line 313 "gnome-pilot-conduit-backup.c"
		}
		g_value_set_pointer (VAL, ARG);
		break;
	}
	default:
/* Apparently in g++ this is needed, glib is b0rk */
#ifndef __PRETTY_FUNCTION__
#  undef G_STRLOC
#  define G_STRLOC	__FILE__ ":" G_STRINGIFY (__LINE__)
#endif
		G_OBJECT_WARN_INVALID_PROPERTY_ID (object, property_id, pspec);
		break;
	}
}
#undef __GOB_FUNCTION__



#line 53 "gnome-pilot-conduit-backup.gob"
GObject * 
gnome_pilot_conduit_backup_new (GPilotPilot * pilot)
{
#line 336 "gnome-pilot-conduit-backup.c"
#define __GOB_FUNCTION__ "Gnome:Pilot:Conduit:Backup::new"
{
#line 54 "gnome-pilot-conduit-backup.gob"
	
		GnomePilotConduitBackup *ret = SELF (g_object_new (TYPE_SELF, 
								   "GnomePilotConduit::pilot", pilot, 
								   NULL));
		return G_OBJECT (ret);
	}}
#line 346 "gnome-pilot-conduit-backup.c"
#undef __GOB_FUNCTION__

#line 62 "gnome-pilot-conduit-backup.gob"
int 
gnome_pilot_conduit_backup_backup (GnomePilotConduitBackup * self, GnomePilotDBInfo * dbinfo)
{
#line 353 "gnome-pilot-conduit-backup.c"
	GValue ___param_values[2];
	GValue ___return_val;

memset (&___return_val, 0, sizeof (___return_val));
memset (&___param_values, 0, sizeof (___param_values));

#line 62 "gnome-pilot-conduit-backup.gob"
	g_return_val_if_fail (self != NULL, (int )0);
#line 62 "gnome-pilot-conduit-backup.gob"
	g_return_val_if_fail (GNOME_IS_PILOT_CONDUIT_BACKUP (self), (int )0);
#line 62 "gnome-pilot-conduit-backup.gob"
	g_return_val_if_fail (dbinfo != NULL, (int )0);
#line 366 "gnome-pilot-conduit-backup.c"

	___param_values[0].g_type = 0;
	g_value_init (&___param_values[0], G_TYPE_FROM_INSTANCE (self));
	g_value_set_instance (&___param_values[0], (gpointer) self);

	___param_values[1].g_type = 0;
	g_value_init (&___param_values[1], G_TYPE_POINTER);
	g_value_set_pointer (&___param_values[1], (gpointer ) dbinfo);

	g_value_init (&___return_val, G_TYPE_INT);

	g_signal_emitv (___param_values,
		object_signals[BACKUP_SIGNAL],
		0 /* detail */,
		&___return_val);

	g_value_unset (&___param_values[0]);
	g_value_unset (&___param_values[1]);

	{
		int  ___ret = (gint ) g_value_get_int (&___return_val);
		g_value_unset (&___return_val);
		return ___ret;
	}
}

#line 66 "gnome-pilot-conduit-backup.gob"
int 
gnome_pilot_conduit_backup_restore (GnomePilotConduitBackup * self, int pisock, char * directory, GnomePilotConduitBackupRestore func, gpointer func_data)
{
#line 397 "gnome-pilot-conduit-backup.c"
	GValue ___param_values[5];
	GValue ___return_val;

memset (&___return_val, 0, sizeof (___return_val));
memset (&___param_values, 0, sizeof (___param_values));

#line 66 "gnome-pilot-conduit-backup.gob"
	g_return_val_if_fail (self != NULL, (int )0);
#line 66 "gnome-pilot-conduit-backup.gob"
	g_return_val_if_fail (GNOME_IS_PILOT_CONDUIT_BACKUP (self), (int )0);
#line 408 "gnome-pilot-conduit-backup.c"

	___param_values[0].g_type = 0;
	g_value_init (&___param_values[0], G_TYPE_FROM_INSTANCE (self));
	g_value_set_instance (&___param_values[0], (gpointer) self);

	___param_values[1].g_type = 0;
	g_value_init (&___param_values[1], G_TYPE_INT);
	g_value_set_int (&___param_values[1], (gint ) pisock);

	___param_values[2].g_type = 0;
	g_value_init (&___param_values[2], G_TYPE_POINTER);
	g_value_set_pointer (&___param_values[2], (gpointer ) directory);

	___param_values[3].g_type = 0;
	g_value_init (&___param_values[3], G_TYPE_POINTER);
	g_value_set_pointer (&___param_values[3], (gpointer ) func);

	___param_values[4].g_type = 0;
	g_value_init (&___param_values[4], G_TYPE_POINTER);
	g_value_set_pointer (&___param_values[4], (gpointer ) func_data);

	g_value_init (&___return_val, G_TYPE_INT);

	g_signal_emitv (___param_values,
		object_signals[RESTORE_SIGNAL],
		0 /* detail */,
		&___return_val);

	g_value_unset (&___param_values[0]);
	g_value_unset (&___param_values[1]);
	g_value_unset (&___param_values[2]);
	g_value_unset (&___param_values[3]);
	g_value_unset (&___param_values[4]);

	{
		int  ___ret = (gint ) g_value_get_int (&___return_val);
		g_value_unset (&___return_val);
		return ___ret;
	}
}
