/* Generated by GOB (v2.0.17)   (do not edit directly) */

/* End world hunger, donate to the World Food Programme, http://www.wfp.org */

#define GOB_VERSION_MAJOR 2
#define GOB_VERSION_MINOR 0
#define GOB_VERSION_PATCHLEVEL 17

#define selfp (self->_priv)

#include <string.h> /* memset() */

#ifdef G_LIKELY
#define ___GOB_LIKELY(expr) G_LIKELY(expr)
#define ___GOB_UNLIKELY(expr) G_UNLIKELY(expr)
#else /* ! G_LIKELY */
#define ___GOB_LIKELY(expr) (expr)
#define ___GOB_UNLIKELY(expr) (expr)
#endif /* G_LIKELY */

#line 29 "gnome-pilot-conduit-file.gob"

#include "gnome-pilot-conduit-file.h"
#include "gnome-pilot-conduit-file-private.h"
#include <sys/stat.h>
#include <unistd.h>
#include <sys/types.h>
#include <utime.h>
#include <pi-file.h>


#line 33 "gnome-pilot-conduit-file.c"
/* self casting macros */
#define SELF(x) GNOME_PILOT_CONDUIT_FILE(x)
#define SELF_CONST(x) GNOME_PILOT_CONDUIT_FILE_CONST(x)
#define IS_SELF(x) GNOME_IS_PILOT_CONDUIT_FILE(x)
#define TYPE_SELF GNOME_TYPE_PILOT_CONDUIT_FILE
#define SELF_CLASS(x) GNOME_PILOT_CONDUIT_FILE_CLASS(x)

#define SELF_GET_CLASS(x) GNOME_PILOT_CONDUIT_FILE_GET_CLASS(x)

/* self typedefs */
typedef GnomePilotConduitFile Self;
typedef GnomePilotConduitFileClass SelfClass;

/* here are local prototypes */
#line 0 "gnome-pilot-conduit-file.gob"
static void gnome_pilot_conduit_file_init (GnomePilotConduitFile * o) G_GNUC_UNUSED;
#line 50 "gnome-pilot-conduit-file.c"
#line 0 "gnome-pilot-conduit-file.gob"
static void gnome_pilot_conduit_file_class_init (GnomePilotConduitFileClass * c) G_GNUC_UNUSED;
#line 53 "gnome-pilot-conduit-file.c"

/*
 * Signal connection wrapper macro shortcuts
 */
#define self_connect__install_db(object,func,data)	gnome_pilot_conduit_file_connect__install_db((object),(func),(data))
#define self_connect_after__install_db(object,func,data)	gnome_pilot_conduit_file_connect_after__install_db((object),(func),(data))
#define self_connect_data__install_db(object,func,data,destroy_data,flags)	gnome_pilot_conduit_file_connect_data__install_db((object),(func),(data),(destroy_data),(flags))

typedef gint  (*___Sig1) (GnomePilotConduitFile *, gint , gpointer , gboolean , gpointer);

static void
___marshal_Sig1 (GClosure *closure,
	GValue *return_value G_GNUC_UNUSED,
	guint n_param_values,
	const GValue *param_values,
	gpointer invocation_hint G_GNUC_UNUSED,
	gpointer marshal_data)
{
	gint  v_return;
	register ___Sig1 callback;
	register GCClosure *cc = (GCClosure*) closure;
	register gpointer data1, data2;

	g_return_if_fail (n_param_values == 4);

	if (G_CCLOSURE_SWAP_DATA (closure)) {
		data1 = closure->data;
		data2 = g_value_peek_pointer (param_values + 0);
	} else {
		data1 = g_value_peek_pointer (param_values + 0);
		data2 = closure->data;
	}

	callback = (___Sig1) (marshal_data != NULL ? marshal_data : cc->callback);

	v_return = callback ((GnomePilotConduitFile *)data1,
		(gint ) g_value_get_int (param_values + 1),
		(gpointer ) g_value_get_pointer (param_values + 2),
		(gboolean ) g_value_get_boolean (param_values + 3),
		data2);

	g_value_set_int (return_value, v_return);
}


enum {
	INSTALL_DB_SIGNAL,
	LAST_SIGNAL
};

static guint object_signals[LAST_SIGNAL] = {0};

/* pointer to the class of our parent */
static GnomePilotConduitClass *parent_class = NULL;

/* Short form macros */
#define self_new gnome_pilot_conduit_file_new
#define self_install_db gnome_pilot_conduit_file_install_db
GType
gnome_pilot_conduit_file_get_type (void)
{
	static GType type = 0;

	if ___GOB_UNLIKELY(type == 0) {
		static const GTypeInfo info = {
			sizeof (GnomePilotConduitFileClass),
			(GBaseInitFunc) NULL,
			(GBaseFinalizeFunc) NULL,
			(GClassInitFunc) gnome_pilot_conduit_file_class_init,
			(GClassFinalizeFunc) NULL,
			NULL /* class_data */,
			sizeof (GnomePilotConduitFile),
			0 /* n_preallocs */,
			(GInstanceInitFunc) gnome_pilot_conduit_file_init,
			NULL
		};

		type = g_type_register_static (GNOME_TYPE_PILOT_CONDUIT, "GnomePilotConduitFile", &info, (GTypeFlags)0);
	}

	return type;
}

/* a macro for creating a new object of our type */
#define GET_NEW ((GnomePilotConduitFile *)g_object_new(gnome_pilot_conduit_file_get_type(), NULL))

/* a function for creating a new object of our type */
#include <stdarg.h>
static GnomePilotConduitFile * GET_NEW_VARG (const char *first, ...) G_GNUC_UNUSED;
static GnomePilotConduitFile *
GET_NEW_VARG (const char *first, ...)
{
	GnomePilotConduitFile *ret;
	va_list ap;
	va_start (ap, first);
	ret = (GnomePilotConduitFile *)g_object_new_valist (gnome_pilot_conduit_file_get_type (), first, ap);
	va_end (ap);
	return ret;
}

static void 
gnome_pilot_conduit_file_init (GnomePilotConduitFile * o G_GNUC_UNUSED)
{
#define __GOB_FUNCTION__ "Gnome:Pilot:Conduit:File::init"
}
#undef __GOB_FUNCTION__
static void 
gnome_pilot_conduit_file_class_init (GnomePilotConduitFileClass * c G_GNUC_UNUSED)
{
#define __GOB_FUNCTION__ "Gnome:Pilot:Conduit:File::class_init"
	GObjectClass *g_object_class G_GNUC_UNUSED = (GObjectClass*) c;

	parent_class = g_type_class_ref (GNOME_TYPE_PILOT_CONDUIT);

	object_signals[INSTALL_DB_SIGNAL] =
		g_signal_new ("install_db",
			G_TYPE_FROM_CLASS (g_object_class),
			(GSignalFlags)(G_SIGNAL_RUN_LAST | G_SIGNAL_ACTION),
			G_STRUCT_OFFSET (GnomePilotConduitFileClass, install_db),
			NULL, NULL,
			___marshal_Sig1,
			G_TYPE_INT, 3,
			G_TYPE_INT,
			G_TYPE_POINTER,
			G_TYPE_BOOLEAN);
	if ___GOB_UNLIKELY(sizeof(int ) != sizeof(gint ) || sizeof(int ) != sizeof(gint ) || sizeof(gchar * ) != sizeof(gpointer ) || sizeof(gboolean ) != sizeof(gboolean ) || parent_class == NULL /* avoid warning */) {
		g_error("gnome-pilot-conduit-file.gob line 50: Type mismatch of \"install_db\" signal signature");
	}

	c->install_db = NULL;
}
#undef __GOB_FUNCTION__



#line 41 "gnome-pilot-conduit-file.gob"
GObject * 
gnome_pilot_conduit_file_new (GPilotPilot * pilot)
{
#line 193 "gnome-pilot-conduit-file.c"
#define __GOB_FUNCTION__ "Gnome:Pilot:Conduit:File::new"
{
#line 42 "gnome-pilot-conduit-file.gob"
	
		GnomePilotConduitFile *ret = SELF (g_object_new (TYPE_SELF, 
								   "GnomePilotConduit::pilot", pilot, 
								   NULL));
		return G_OBJECT (ret);
	}}
#line 203 "gnome-pilot-conduit-file.c"
#undef __GOB_FUNCTION__

#line 50 "gnome-pilot-conduit-file.gob"
int 
gnome_pilot_conduit_file_install_db (GnomePilotConduitFile * self, int pisock, gchar * src_file, gboolean rm)
{
#line 210 "gnome-pilot-conduit-file.c"
	GValue ___param_values[4];
	GValue ___return_val;

memset (&___return_val, 0, sizeof (___return_val));
memset (&___param_values, 0, sizeof (___param_values));

#line 50 "gnome-pilot-conduit-file.gob"
	g_return_val_if_fail (self != NULL, (int )0);
#line 50 "gnome-pilot-conduit-file.gob"
	g_return_val_if_fail (GNOME_IS_PILOT_CONDUIT_FILE (self), (int )0);
#line 221 "gnome-pilot-conduit-file.c"

	___param_values[0].g_type = 0;
	g_value_init (&___param_values[0], G_TYPE_FROM_INSTANCE (self));
	g_value_set_instance (&___param_values[0], (gpointer) self);

	___param_values[1].g_type = 0;
	g_value_init (&___param_values[1], G_TYPE_INT);
	g_value_set_int (&___param_values[1], (gint ) pisock);

	___param_values[2].g_type = 0;
	g_value_init (&___param_values[2], G_TYPE_POINTER);
	g_value_set_pointer (&___param_values[2], (gpointer ) src_file);

	___param_values[3].g_type = 0;
	g_value_init (&___param_values[3], G_TYPE_BOOLEAN);
	g_value_set_boolean (&___param_values[3], (gboolean ) rm);

	g_value_init (&___return_val, G_TYPE_INT);

	g_signal_emitv (___param_values,
		object_signals[INSTALL_DB_SIGNAL],
		0 /* detail */,
		&___return_val);

	g_value_unset (&___param_values[0]);
	g_value_unset (&___param_values[1]);
	g_value_unset (&___param_values[2]);
	g_value_unset (&___param_values[3]);

	{
		int  ___ret = (gint ) g_value_get_int (&___return_val);
		g_value_unset (&___return_val);
		return ___ret;
	}
}
