/* Generated by GOB (v2.0.17)   (do not edit directly) */

#ifndef __GNOME_PILOT_CONDUIT_CONFIG_PRIVATE_H__
#define __GNOME_PILOT_CONDUIT_CONFIG_PRIVATE_H__

#include "gnome-pilot-conduit-config.h"

#ifdef __cplusplus
extern "C" {
#endif /* __cplusplus */

struct _GnomePilotConduitConfigPrivate {
#line 42 "gnome-pilot-conduit-config.gob"
	guint32 pilot_id;
#line 43 "gnome-pilot-conduit-config.gob"
	GnomePilotConduitManagement * gpcm;
#line 18 "gnome-pilot-conduit-config-private.h"
};

#ifdef __cplusplus
}
#endif /* __cplusplus */

#endif
