/* Generated by GOB (v2.0.17)   (do not edit directly) */

#include <glib.h>
#include <glib-object.h>
#ifndef __GNOME_PILOT_CONDUIT_CONFIG_H__
#define __GNOME_PILOT_CONDUIT_CONFIG_H__

#ifdef __cplusplus
extern "C" {
#endif /* __cplusplus */



#include <glib.h>
#include <gnome-pilot-conduit.h>
#include <gnome-pilot-config.h>
#include <gnome-pilot-conduit-management.h>
#include <gmodule.h>


/*
 * Type checking and casting macros
 */
#define GNOME_TYPE_PILOT_CONDUIT_CONFIG	(gnome_pilot_conduit_config_get_type())
#define GNOME_PILOT_CONDUIT_CONFIG(obj)	G_TYPE_CHECK_INSTANCE_CAST((obj), gnome_pilot_conduit_config_get_type(), GnomePilotConduitConfig)
#define GNOME_PILOT_CONDUIT_CONFIG_CONST(obj)	G_TYPE_CHECK_INSTANCE_CAST((obj), gnome_pilot_conduit_config_get_type(), GnomePilotConduitConfig const)
#define GNOME_PILOT_CONDUIT_CONFIG_CLASS(klass)	G_TYPE_CHECK_CLASS_CAST((klass), gnome_pilot_conduit_config_get_type(), GnomePilotConduitConfigClass)
#define GNOME_IS_PILOT_CONDUIT_CONFIG(obj)	G_TYPE_CHECK_INSTANCE_TYPE((obj), gnome_pilot_conduit_config_get_type ())

#define GNOME_PILOT_CONDUIT_CONFIG_GET_CLASS(obj)	G_TYPE_INSTANCE_GET_CLASS((obj), gnome_pilot_conduit_config_get_type(), GnomePilotConduitConfigClass)

/* Private structure type */
typedef struct _GnomePilotConduitConfigPrivate GnomePilotConduitConfigPrivate;

/*
 * Main object structure
 */
#ifndef __TYPEDEF_GNOME_PILOT_CONDUIT_CONFIG__
#define __TYPEDEF_GNOME_PILOT_CONDUIT_CONFIG__
typedef struct _GnomePilotConduitConfig GnomePilotConduitConfig;
#endif
struct _GnomePilotConduitConfig {
	GObject __parent__;
	/*< public >*/
	GnomePilotConduitSyncType sync_type;
	GnomePilotConduitSyncType first_sync_type;
	gboolean first_slow;
	/*< private >*/
	GnomePilotConduitConfigPrivate *_priv;
};

/*
 * Class definition
 */
typedef struct _GnomePilotConduitConfigClass GnomePilotConduitConfigClass;
struct _GnomePilotConduitConfigClass {
	GObjectClass __parent__;
};


/*
 * Public methods
 */
GType	gnome_pilot_conduit_config_get_type	(void) G_GNUC_CONST;
#line 49 "gnome-pilot-conduit-config.gob"
const gchar * 	gnome_pilot_conduit_config_sync_type_int_to_str	(GnomePilotConduitSyncType e);
#line 68 "gnome-pilot-conduit-config.h"
#line 73 "gnome-pilot-conduit-config.gob"
gint 	gnome_pilot_conduit_config_sync_type_str_to_int	(gchar * s);
#line 71 "gnome-pilot-conduit-config.h"
#line 101 "gnome-pilot-conduit-config.gob"
GnomePilotConduitConfig * 	gnome_pilot_conduit_config_new	(GnomePilotConduitManagement * gpcm,
					guint32 pilot_id);
#line 75 "gnome-pilot-conduit-config.h"
#line 115 "gnome-pilot-conduit-config.gob"
void 	gnome_pilot_conduit_config_destroy	(GnomePilotConduitConfig * self);
#line 78 "gnome-pilot-conduit-config.h"
#line 125 "gnome-pilot-conduit-config.gob"
int 	gnome_pilot_conduit_config_load_config	(GnomePilotConduitConfig * self);
#line 81 "gnome-pilot-conduit-config.h"
#line 154 "gnome-pilot-conduit-config.gob"
int 	gnome_pilot_conduit_config_save_config	(GnomePilotConduitConfig * self);
#line 84 "gnome-pilot-conduit-config.h"
#line 186 "gnome-pilot-conduit-config.gob"
gboolean 	gnome_pilot_conduit_config_is_enabled	(GnomePilotConduitConfig * self,
					GnomePilotConduitSyncType * sync_type);
#line 88 "gnome-pilot-conduit-config.h"
#line 237 "gnome-pilot-conduit-config.gob"
void 	gnome_pilot_conduit_config_enable	(GnomePilotConduitConfig * self,
					GnomePilotConduitSyncType sync_type);
#line 92 "gnome-pilot-conduit-config.h"
#line 292 "gnome-pilot-conduit-config.gob"
void 	gnome_pilot_conduit_config_enable_with_first_sync	(GnomePilotConduitConfig * self,
					GnomePilotConduitSyncType sync_type,
					GnomePilotConduitSyncType first_sync_type,
					gboolean slow);
#line 98 "gnome-pilot-conduit-config.h"
#line 319 "gnome-pilot-conduit-config.gob"
void 	gnome_pilot_conduit_config_remove_first_sync	(GnomePilotConduitConfig * self);
#line 101 "gnome-pilot-conduit-config.h"
#line 340 "gnome-pilot-conduit-config.gob"
void 	gnome_pilot_conduit_config_disable	(GnomePilotConduitConfig * self);
#line 104 "gnome-pilot-conduit-config.h"

#ifdef __cplusplus
}
#endif /* __cplusplus */

#endif
