/* Generated by GOB (v2.0.17)   (do not edit directly) */

#ifndef __GNOME_PILOT_CLIENT_PRIVATE_H__
#define __GNOME_PILOT_CLIENT_PRIVATE_H__

#include "gnome-pilot-client.h"

#ifdef __cplusplus
extern "C" {
#endif /* __cplusplus */


#ifdef __cplusplus
}
#endif /* __cplusplus */

#endif
